name: mobile_app
description: Travel-Mate Tourist Node
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.0
  sensors_plus: ^7.0.0
  mappls_gl: ^1.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  geolocator: ^14.0.2
  flutter_background_service: ^5.0.5
  vibration: ^3.1.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tflite_models/
